// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace blog {
	
	
	public partial class Categories {
		
		protected System.Web.UI.WebControls.Repeater WelcomeControl;
		
		//protected System.Web.UI.HtmlControls.HtmlForm EditCategory;
		protected System.Web.UI.WebControls.Repeater EditCategoryControl;
		protected System.Web.UI.WebControls.Repeater CategoryTableControl;
		
		protected System.Web.UI.WebControls.Repeater FooterControl;
	}
}
