// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace blog {
	
	
	public partial class EditPost {
		
		protected System.Web.UI.WebControls.Repeater WelcomeControl;
		
		protected System.Web.UI.HtmlControls.HtmlForm catFrm;
		
		protected System.Web.UI.WebControls.Repeater ContentControl;
		
		protected System.Web.UI.WebControls.DropDownList CategoryControl;
		
		protected System.Web.UI.WebControls.Repeater EditControl;
		protected System.Web.UI.WebControls.Repeater NewsControl;
		protected System.Web.UI.WebControls.Repeater FooterControl;
	}
}
